export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  TIMEOUT = 'TIMEOUT',
  USER_INPUT_ERROR = 'USER_INPUT_ERROR'
}
